[Go Test Issues] Update go_test_wrapper.sh to use the go_1_18 path of test2json
Summary:
The tests seem to fail that the go_1_16 based directory for test2json is not found

I'm not sure if any others have re believe this would affect changes test info extraction for all **go** tests.

**Motivation**

We noticed some issues with our tests not properly picking up the test targets from some of our filesystem changes builds and instead simply returning "exit status 1".

See report by @pindi in https://jira.dropboxer.net/browse/DEVHELP-1343

From timing it appears this started right at the commit that `testrunner.go` and other files were upgraded from Go 1.16 to go 1.17 in D836958 (/ later Go 1.18 in D838577.)

From comparing builds, an initial signal of the change (noticed by @yuanlu, thanks!) was a new line of "Overwriting XML because it has no errors" in the test output coming from this part of the testrunner:
https://sourcegraph.pp.dropbox.com/server/-/blob/go/src/dropbox/devtools/testrunner/testrunner.go?L393:14

It took quite a bit of parsing, but I believe the root problem is the "not found" message during a test2json step of the go_test_wrapper.sh

**Root issue this fixes**:

`go_1_16_linux_amd64_tar_gz/go/pkg/tool/linux_amd64/test2json: No such file or directory`

This is outside my typical knowledge I'm not sure how such tooling packaging works, but changing the expected path here in in go_test_wrapper.sh appears to fix the error and I figured I't write up the patch.

I'd like to try this and see if it helps fix the changes ui extraction of our test failures. Let us know if you have other insights, thanks!

Full message from logoutput

```
/dev/shm/bazel-sandbox.5f83260c3b85bf767c533eeb674aac04423be84455d6543f1b9b7b6dd0dc7e5f/linux-sandbox/22280/execroot/__main__/bazel-out/k8-fastbuild/bin/go/src/dropbox/filesystem/random_checker/random_checker_test_1.16.runfiles/__main__/build_tools/go/go_test_wrapper.sh: line 23: /dev/shm/bazel-sandbox.5f83260c3b85bf767c533eeb674aac04423be84455d6543f1b9b7b6dd0dc7e5f/linux-sandbox/22280/execroot/__main__/bazel-out/k8-fastbuild/bin/go/src/dropbox/filesystem/random_checker/random_checker_test_1.16.runfiles/__main__/../go_1_16_linux_amd64_tar_gz/go/pkg/tool/linux_amd64/test2json: No such file or directory
```

Test Plan:
The change in behavior repro's locally:
Using our test `mbzl test //go/src/dropbox/filesystem/random_checker:random_checker_test`
simplified to fail immeditaely

Before:

```
--- FAIL: TestRandomChecker (0.00s)
FAIL
/dev/shm/bazel-sandbox.d6caac357997fb040f9ea341e82aad3f81d0441620b6e2438a13363edc0513d3/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/go/src/dropbox/filesystem/random_checker/random_checker_test_1.16.runfiles/__main__/build_tools/go/go_test_wrapper.sh: line 23: /dev/shm/bazel-sandbox.d6caac357997fb040f9ea341e82aad3f81d0441620b6e2438a13363edc0513d3/linux-sandbox/8/execroot/__main__/bazel-out/k8-fastbuild/bin/go/src/dropbox/filesystem/random_checker/random_checker_test_1.16.runfiles/__main__/../go_1_16_linux_amd64_tar_gz/go/pkg/tool/linux_amd64/test2json: No such file or directory
23:14:20.639474 svcinit.go:528: Encountered error during test run: exit status 1
23:14:20.736257 svcinit.go:331: Shutting down service controller
23:14:20.738556 svcinit.go:334: Services resource utilization: User: 51.177673s System: 11.842423s
23:14:20.739597 testrunner.go:348: Max RSS memory used: 4053417984 bytes
23:14:20.739632 testrunner.go:361: exit status 1
23:14:20.741761 testrunner.go:395: Overwriting XML because it has no errors.
================================================================================
```

Same run after this diff:
```
--- FAIL: TestRandomChecker (0.00s)
FAIL
23:22:20.872532 svcinit.go:528: Encountered error during test run: exit status 1
23:22:20.969531 svcinit.go:331: Shutting down service controller
23:22:20.972014 svcinit.go:334: Services resource utilization: User: 51.300443s System: 12.010392s
23:22:20.973018 testrunner.go:348: Max RSS memory used: 4025778176 bytes
23:22:20.973051 testrunner.go:361: exit status 1
================================================================================
```
GitOrigin-RevId: e91345defbfb281d3fc32660f4468a85c28701c2